import Head from "next/head";
import { Inter } from "next/font/google";
import ScrollTrigger from "react-scroll-trigger";
import { useCallback, useState } from "react";
import Header from "@/components/header";
import Slider from "@/components/slider";
import WhyChouseUs from "@/components/whyChouseUs";
import Swap from "@/components/swap";
import Tokenomic from "@/components/tokenomic";
import About from "@/components/about";
import Desc from "@/components/desc";
import Footer from "@/components/footer";
import ContactUs from "@/components/contactUs";
import copy from "clipboard-copy";
import { toast } from "react-toastify";

// const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  const { ethereumClient } = props;
  const text = "0x297A453293505b19c7A1EdA5E039268da06a1D58";
  const handleCopy = useCallback(() => {
    copy(text);
    toast.success("Copied");
  }, [text]);

  const [animatedbox, setAnimatedbox] = useState(false);

  const onEnterBox = () => {
    setAnimatedbox(true);
  };

  const onExitBox = () => {
    setAnimatedbox(false);
  };
  return (
    <>
      <Head>
        <title>DOGINU</title>
        <meta name="description" content="Generated by DOGINU" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div>
        <Header />
        <Slider />
        <div
          id="airdrop"
          className="p-0 m-0 py-5 row justify-content-center px-0 w-100"
        >
          <div className="col-lg-5 col-sm-10 col-10 px-0 p-5 text-white ">
            <ScrollTrigger onEnter={onEnterBox} onExit={onExitBox}>
              <div
                className={`box_container_parrent p-2 p-md-4 ${
                  animatedbox && " animate_center"
                }`}
              >
                <div className={`box_container p-3 p-lg-4 `}>
                  <span className="box_title pb-3 d-flex justify-content-start align-items-center">
                    <img
                      className="me-2"
                      style={{ width: "45px" }}
                      src="/logo.png"
                    />
                    <b> Airdrop</b>
                  </span>

                  <p
                    style={{
                      color: "yellow",
                      fontWeight: "500",
                      fontSize: "20px",
                    }}
                  >
                    35% of DogInu supply will be airdropped. You can claim
                    DogInu tokens 25/1/2024
                  </p>
                  <br />
                  <p
                    style={{
                      color: "yellow",
                      fontWeight: "500",
                      fontSize: "20px",
                    }}
                  >
                    DogInu tokens that have not been claimed within 30 days will
                    be used for the Community Long-Term Incentive Reward
                    Program.
                  </p>

                  <br />

                  <ul>
                    <li className="fw-bold fs-5 text-warning">
                      20% AVAX Staker
                    </li>
                    <li className="fw-bold fs-5 text-warning">
                      10% JOE Staker
                    </li>
                    <li className="fw-bold fs-5 text-warning">5% Community</li>
                  </ul>
                  <br />

                  <div className="d-flex flex-wrap justify-content-between">
                    <span>Recived</span>
                    <span>0</span>
                    <div
                      style={{ background: "#999" }}
                      className="w-100 p-2 rounded"
                    ></div>
                  </div>

                  <div className="d-flex justify-content-center  pt-5">
                    <button className="p-3  px-3 text-center button_home w-100">
                      Claim
                    </button>
                  </div>
                </div>
              </div>
            </ScrollTrigger>
          </div>
        </div>

        <Swap ethereumClient={ethereumClient} />

        <WhyChouseUs />
        <Tokenomic />
        <Desc />
        <Footer />
      </div>
    </>
  );
}
